@hostname=localhost:3333
@prefix=dev
@base_url={{hostname}}/{{prefix}}

### @name schema_build
POST http://{{base_url}}/schemas/build
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"

file
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="teste.xml"
Content-Type: text/xml

< ./modelos/teste.xml
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### @name schema_paginate
GET http://{{base_url}}/schemas/paginate

### @name auth_register
POST http://{{base_url}}/auth/register
Content-Type: application/json

{
  "password": "123123",
  "email": "admin@mail.com"
}

### @name auth_login
POST http://{{base_url}}/auth/login
Content-Type: application/json

{
  "password": "123123",
  "email": "admin@mail.com"
}
